server:
    port: 8080
    address: 0.0.0.0
    servlet:
        context-path: /smart-school-bus

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/ssb"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    key: ${JWT_KEY}
    expiration-time: 3600 #seconds
    refreshExpiration-time: 604800 #seconds