server:
    port: 8080
    servlet:
        context-path: /smart-school-bus

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/ssb"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    key: "JWGfJPd4nzAOWfBu7rmcc6ACoygdlec3b/bD43D6/uLlf3ebn+5J29iUhpPOJ1BQ"
    expiration-time: 3600 #seconds
    refreshExpiration-time: 604800 #seconds